name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run-java:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
      - run: java Tests.java
